version: '3.3'
services:
  web:
    image: "web"
    ports:
     - "80:80"
    volumes:
     - ./web:/app:ro
  core:
    image: "core"
    command: "debug"
    ports:
     - "5005:5005"
    volumes:
     - ./logs/core:/app/logs:rw
     - ./models/dialogue:/app/dialogue:ro
    depends_on:
     - nlu
  nlu:
    image: "nlu"
    command: "debug"
    ports:
     - "5000:5000"
    volumes:
     - ./logs/nlu:/app/logs:rw
     - ./models/nlu:/app/projects:ro


