version: "3.1"

services:

  logstash:
    image: logstashimage
    volumes:
          - ./:/config
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    networks:
      default:
        ipv4_address: 172.21.0.7
        aliases:
          - "logstash"

  elasticsearch:
    image: elasticsearch:6.5.2
    ports:
      - "9200:9200"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

  kibana:
    image: kibana:6.5.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16